# /etc/modprobe.d/hardening.conf
# Disable rarely used and legacy network protocols vulnerable to privilege escalation (CIS Benchmark)

install dccp /bin/true
install sctp /bin/true
install rds /bin/true
install tipc /bin/true
install firewire-core /bin/true
